//_\TLV_version 1d: tl-x.org, generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro
//_\source top.tlv 40

//_\SV
   // Include Tiny Tapeout Lab.
   // Included URL: "https://raw.githubusercontent.com/os-fpga/Virtual-FPGA-Lab/35e36bd144fddd75495d4cbc01c4fc50ac5bde6f/tlv_lib/tiny_tapeout_lib.tlv"// Included URL: "https://raw.githubusercontent.com/os-fpga/Virtual-FPGA-Lab/a069f1e4e19adc829b53237b3e0b5d6763dc3194/tlv_lib/fpga_includes.tlv"
//_\source top.tlv 212

//_\SV

// ================================================
// A simple Makerchip Verilog test bench driving random stimulus.
// Modify the module contents to your needs.
// ================================================

module top(input logic clk, input logic reset, input logic [31:0] cyc_cnt, output logic passed, output logic failed);
   // Tiny tapeout I/O signals.
   logic [7:0] ui_in, uo_out;
   
   logic [31:0] r;
   always @(posedge clk) r <= 0;
   assign ui_in = 8'b00000001;
   
   logic ena = 1'b0;
   logic rst_n = ! reset;

   /*
   // Or, to provide specific inputs at specific times (as for lab C-TB) ...
   // BE SURE TO COMMENT THE ASSIGNMENT OF INPUTS ABOVE.
   // BE SURE TO DRIVE THESE ON THE B-PHASE OF THE CLOCK (ODD STEPS).
   // Driving on the rising clock edge creates a race with the clock that has unpredictable simulation behavior.
   initial begin
      #1  // Drive inputs on the B-phase.
         ui_in = 4'h0;
      #10 // Step 5 cycles, past reset.
         ui_in = 4'hFF;
      // ...etc.
   end
   */

   // Instantiate the Tiny Tapeout module.
   tt_um_template tt(.*);

   //assign passed = top.cyc_cnt > 60;
   assign failed = 1'b0;
endmodule


// Provide a wrapper module to debounce input signals if requested.

//_\SV



// =======================
// The Tiny Tapeout module
// =======================

module tt_um_template (
    input  wire [7:0] ui_in,    // Dedicated inputs - connected to the input switches
    output wire [7:0] uo_out,   // Dedicated outputs - connected to the 7 segment display
    /*   // The FPGA is based on TinyTapeout 3 which has no bidirectional I/Os (vs. TT6 for the ASIC).
    input  wire [7:0] uio_in,   // IOs: Bidirectional Input path
    output wire [7:0] uio_out,  // IOs: Bidirectional Output path
    output wire [7:0] uio_oe,   // IOs: Bidirectional Enable path (active high: 0=input, 1=output)
    */
    input  wire       ena,      // will go high when the design is enabled
    input  wire       clk,      // clock
    input  wire       rst_n     // reset_n - low to reset
);
   wire reset = ! rst_n;

// ---------- Generated Code Inlined Here (before 1st \TLV) ----------
// Generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro from Redwood EDA, LLC.
// (Installed here: /usr/local/mono/sandpiper/distro.)
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


// For silencing unused signal messages.
`define BOGUS_USE(ignore)


genvar digit, input_label, leds, switch;


//
// Signals declared top-level.
//

// For $slideswitch.
logic [7:0] L0_slideswitch_a0;

// For $sseg_decimal_point_n.
logic L0_sseg_decimal_point_n_a0;

// For $sseg_digit_n.
logic [7:0] L0_sseg_digit_n_a0;

// For $sseg_segment_n.
logic [6:0] L0_sseg_segment_n_a0;

// For /fpga_pins/fpga|clock_time$cycounter.
logic [24:0] FpgaPins_Fpga_CLOCK_TIME_cycounter_a0,
             FpgaPins_Fpga_CLOCK_TIME_cycounter_a1;

// For /fpga_pins/fpga|clock_time$digit.
logic [7:0] FpgaPins_Fpga_CLOCK_TIME_digit_a0,
            FpgaPins_Fpga_CLOCK_TIME_digit_a1;

// For /fpga_pins/fpga|clock_time$pulse.
logic FpgaPins_Fpga_CLOCK_TIME_pulse_a0;

// For /fpga_pins/fpga|clock_time$reset.
logic FpgaPins_Fpga_CLOCK_TIME_reset_a0;




   //
   // Scope: /fpga_pins
   //


      //
      // Scope: /fpga
      //


         //
         // Scope: |clock_time
         //

            // Staging of $cycounter.
            always_ff @(posedge clk) FpgaPins_Fpga_CLOCK_TIME_cycounter_a1[24:0] <= FpgaPins_Fpga_CLOCK_TIME_cycounter_a0[24:0];

            // Staging of $digit.
            always_ff @(posedge clk) FpgaPins_Fpga_CLOCK_TIME_digit_a1[7:0] <= FpgaPins_Fpga_CLOCK_TIME_digit_a0[7:0];








//
// Debug Signals
//

   if (1) begin : DEBUG_SIGS_GTKWAVE

      (* keep *) logic [7:0] \@0$slideswitch ;
      assign \@0$slideswitch = L0_slideswitch_a0;
      (* keep *) logic  \@0$sseg_decimal_point_n ;
      assign \@0$sseg_decimal_point_n = L0_sseg_decimal_point_n_a0;
      (* keep *) logic [7:0] \@0$sseg_digit_n ;
      assign \@0$sseg_digit_n = L0_sseg_digit_n_a0;
      (* keep *) logic [6:0] \@0$sseg_segment_n ;
      assign \@0$sseg_segment_n = L0_sseg_segment_n_a0;

      //
      // Scope: /digit[0:0]
      //
      for (digit = 0; digit <= 0; digit++) begin : \/digit 

         //
         // Scope: /leds[7:0]
         //
         for (leds = 0; leds <= 7; leds++) begin : \/leds 
            (* keep *) logic  \//@0$viz_lit ;
            assign \//@0$viz_lit = L1_Digit[digit].L2_Leds[leds].L2_viz_lit_a0;
         end
      end

      //
      // Scope: /fpga_pins
      //
      if (1) begin : \/fpga_pins 

         //
         // Scope: /fpga
         //
         if (1) begin : \/fpga 

            //
            // Scope: |clock_time
            //
            if (1) begin : P_clock_time
               (* keep *) logic [24:0] \///@0$cycounter ;
               assign \///@0$cycounter = FpgaPins_Fpga_CLOCK_TIME_cycounter_a0;
               (* keep *) logic [7:0] \///@0$digit ;
               assign \///@0$digit = FpgaPins_Fpga_CLOCK_TIME_digit_a0;
               (* keep *) logic  \///@0$pulse ;
               assign \///@0$pulse = FpgaPins_Fpga_CLOCK_TIME_pulse_a0;
               (* keep *) logic  \///@0$reset ;
               assign \///@0$reset = FpgaPins_Fpga_CLOCK_TIME_reset_a0;
            end
         end
      end

      //
      // Scope: /switch[7:0]
      //
      for (switch = 0; switch <= 7; switch++) begin : \/switch 
         (* keep *) logic  \/@0$viz_switch ;
         assign \/@0$viz_switch = L1_Switch[switch].L1_viz_switch_a0;
      end


   end

// ---------- Generated Code Ends ----------
//_\TLV
   /* verilator lint_off UNOPTFLAT */
   // Connect Tiny Tapeout I/Os to Virtual FPGA Lab.
   //_\source /raw.githubusercontent.com/osfpga/VirtualFPGALab/35e36bd144fddd75495d4cbc01c4fc50ac5bde6f/tlvlib/tinytapeoutlib.tlv 76   // Instantiated from top.tlv, 281 as: m5+tt_connections()
      assign L0_slideswitch_a0[7:0] = ui_in;
      assign L0_sseg_segment_n_a0[6:0] = ~ uo_out[6:0];
      assign L0_sseg_decimal_point_n_a0 = ~ uo_out[7];
      assign L0_sseg_digit_n_a0[7:0] = 8'b11111110;
   //_\end_source

   // Instantiate the Virtual FPGA Lab.
   //_\source /raw.githubusercontent.com/osfpga/VirtualFPGALab/a069f1e4e19adc829b53237b3e0b5d6763dc3194/tlvlib/fpgaincludes.tlv 307   // Instantiated from top.tlv, 284 as: m5+board(/top, /fpga, 7, $, , calc)
      
      //_\source /raw.githubusercontent.com/osfpga/VirtualFPGALab/a069f1e4e19adc829b53237b3e0b5d6763dc3194/tlvlib/fpgaincludes.tlv 355   // Instantiated from /raw.githubusercontent.com/osfpga/VirtualFPGALab/a069f1e4e19adc829b53237b3e0b5d6763dc3194/tlvlib/fpgaincludes.tlv, 309 as: m4+thanks(m5__l(309)m5_eval(m5_get(BOARD_THANKS_ARGS)))
         //_/thanks
            
      //_\end_source
      
   
      // Board VIZ.
   
      // Board Image.
      
      //_/fpga_pins
         
         //_/fpga
            //_\source top.tlv 47   // Instantiated from /raw.githubusercontent.com/osfpga/VirtualFPGALab/a069f1e4e19adc829b53237b3e0b5d6763dc3194/tlvlib/fpgaincludes.tlv, 340 as: m4+calc.
               //_|clock_time
                  //_@0
                     assign FpgaPins_Fpga_CLOCK_TIME_reset_a0 = reset || ui_in[7];
            
                     // ======================================================
                     // cycounter = cycle count. If 20khz, then it will count
                     // 20000 cycles per second.
                     // ======================================================
            
                     assign FpgaPins_Fpga_CLOCK_TIME_cycounter_a0[24:0] =
                        (FpgaPins_Fpga_CLOCK_TIME_reset_a0 || FpgaPins_Fpga_CLOCK_TIME_cycounter_a1 == 25'd20000000 - 25'd1) ? 25'b0 :
                         FpgaPins_Fpga_CLOCK_TIME_cycounter_a1 + 1;
            
                     // $pulse = signal we set to pulse once per second
                     assign FpgaPins_Fpga_CLOCK_TIME_pulse_a0 = (FpgaPins_Fpga_CLOCK_TIME_cycounter_a0 == 25'd20000000 - 24'd1);
            
            
                     assign FpgaPins_Fpga_CLOCK_TIME_digit_a0[7:0] = (FpgaPins_Fpga_CLOCK_TIME_reset_a0) ? 8'b0:
                                    !FpgaPins_Fpga_CLOCK_TIME_pulse_a0 ? FpgaPins_Fpga_CLOCK_TIME_digit_a1 :
                                    (FpgaPins_Fpga_CLOCK_TIME_digit_a1 == 8'b11111111) ? 8'b0 :
                                    FpgaPins_Fpga_CLOCK_TIME_digit_a1 + 1;
            
            
            
                     assign uo_out[7:0] =
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd0) ? 8'b0000000 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd1) ? 8'b0000001 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd2) ? 8'b0000010 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd3) ? 8'b0000011 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd4) ? 8'b0000100 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd5) ? 8'b0000101 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd6) ? 8'b0000110 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd7) ? 8'b0000111 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd8) ? 8'b0001000 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd9) ? 8'b0001001 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd10) ? 8'b0001010 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd11) ? 8'b0001011 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd12) ? 8'b0001100 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd13) ? 8'b0001101 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd14) ? 8'b0001110 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd15) ? 8'b0001111 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd16) ? 8'b0010000 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd17) ? 8'b0010001 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd18) ? 8'b0010010 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd19) ? 8'b0010011 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd20) ? 8'b0010100 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd21) ? 8'b0010101 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd22) ? 8'b0010110 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd23) ? 8'b0010111 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd24) ? 8'b0011000 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd25) ? 8'b0011001 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd26) ? 8'b0011010 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd27) ? 8'b0011011 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd28) ? 8'b0011100 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd29) ? 8'b0011101 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd30) ? 8'b0011110 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd31) ? 8'b0011111 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd32) ? 8'b0100000 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd33) ? 8'b0100001 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd34) ? 8'b0100010 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd35) ? 8'b0100011 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd36) ? 8'b0100100 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd37) ? 8'b0100101 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd38) ? 8'b0100110 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd39) ? 8'b0100111 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd40) ? 8'b0101000 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd41) ? 8'b0101001 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd42) ? 8'b0101010 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd43) ? 8'b0101011 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd44) ? 8'b0101100 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd45) ? 8'b0101101 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd46) ? 8'b0101110 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd47) ? 8'b0101111 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd48) ? 8'b0110000 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd49) ? 8'b0110001 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd50) ? 8'b0110010 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd51) ? 8'b0110011 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd52) ? 8'b0110100 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd53) ? 8'b0110101 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd54) ? 8'b0110110 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd55) ? 8'b0110111 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd56) ? 8'b0111000 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd57) ? 8'b0111001 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd58) ? 8'b0111010 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd59) ? 8'b0111011 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd60) ? 8'b0111100 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd61) ? 8'b0111101 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd62) ? 8'b0111110 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd63) ? 8'b0111111 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd64) ? 8'b1000000 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd65) ? 8'b1000001 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd66) ? 8'b1000010 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd67) ? 8'b1000011 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd68) ? 8'b1000100 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd69) ? 8'b1000101 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd70) ? 8'b1000110 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd71) ? 8'b1000111 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd72) ? 8'b1001000 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd73) ? 8'b1001001 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd74) ? 8'b1001010 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd75) ? 8'b1001011 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd76) ? 8'b1001100 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd77) ? 8'b1001101 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd78) ? 8'b1001110 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd79) ? 8'b1001111 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd80) ? 8'b1010000 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd81) ? 8'b1010001 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd82) ? 8'b1010010 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd83) ? 8'b1010011 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd84) ? 8'b1010100 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd85) ? 8'b1010101 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd86) ? 8'b1010110 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd87) ? 8'b1010111 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd88) ? 8'b1011000 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd89) ? 8'b1011001 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd90) ? 8'b1011010 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd91) ? 8'b1011011 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd92) ? 8'b1011100 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd93) ? 8'b1011101 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd94) ? 8'b1011110 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd95) ? 8'b1011111 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd96) ? 8'b1100000 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd97) ? 8'b1100001 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd98) ? 8'b1100010 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd99) ? 8'b1100011 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd100) ? 8'b1100100 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd101) ? 8'b1100101 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd102) ? 8'b1100110 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd103) ? 8'b1100111 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd104) ? 8'b1101000 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd105) ? 8'b1101001 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd106) ? 8'b1101010 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd107) ? 8'b1101011 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd108) ? 8'b1101100 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd109) ? 8'b1101101 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd110) ? 8'b1101110 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd111) ? 8'b1101111 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd112) ? 8'b1110000 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd113) ? 8'b1110001 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd114) ? 8'b1110010 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd115) ? 8'b1110011 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd116) ? 8'b1110100 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd117) ? 8'b1110101 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd118) ? 8'b1110110 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd119) ? 8'b1110111 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd120) ? 8'b1111000 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd121) ? 8'b1111001 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd122) ? 8'b1111010 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd123) ? 8'b1111011 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd124) ? 8'b1111100 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd125) ? 8'b1111101 :
                        (FpgaPins_Fpga_CLOCK_TIME_digit_a0 == 8'd126) ? 8'b1111110 :
                        8'b1111111;
            
            
            
               // Note that pipesignals assigned here can be found under /fpga_pins/fpga.
            
            
            
            
               // Connect Tiny Tapeout outputs. Note that uio_ outputs are not available in the Tiny-Tapeout-3-based FPGA boards.
               //*uo_out = 8'b0;
               
               
            //_\end_source
   
      // LEDs.
      
   
      // 7-Segment
      //_\source /raw.githubusercontent.com/osfpga/VirtualFPGALab/a069f1e4e19adc829b53237b3e0b5d6763dc3194/tlvlib/fpgaincludes.tlv 395   // Instantiated from /raw.githubusercontent.com/osfpga/VirtualFPGALab/a069f1e4e19adc829b53237b3e0b5d6763dc3194/tlvlib/fpgaincludes.tlv, 346 as: m4+fpga_sseg.
         for (digit = 0; digit <= 0; digit++) begin : L1_Digit //_/digit
            
            for (leds = 0; leds <= 7; leds++) begin : L2_Leds //_/leds

               // For $viz_lit.
               logic L2_viz_lit_a0;

               assign L2_viz_lit_a0 = (! L0_sseg_digit_n_a0[digit]) && ! ((leds == 7) ? L0_sseg_decimal_point_n_a0 : L0_sseg_segment_n_a0[leds % 7]);
               
            end
         end
      //_\end_source
   
      // slideswitches
      //_\source /raw.githubusercontent.com/osfpga/VirtualFPGALab/a069f1e4e19adc829b53237b3e0b5d6763dc3194/tlvlib/fpgaincludes.tlv 454   // Instantiated from /raw.githubusercontent.com/osfpga/VirtualFPGALab/a069f1e4e19adc829b53237b3e0b5d6763dc3194/tlvlib/fpgaincludes.tlv, 349 as: m4+fpga_switch.
         for (switch = 0; switch <= 7; switch++) begin : L1_Switch //_/switch

            // For $viz_switch.
            logic L1_viz_switch_a0;

            assign L1_viz_switch_a0 = L0_slideswitch_a0[switch];
            
         end
      //_\end_source
   
      // pushbuttons
      
   //_\end_source
   // Label the switch inputs [0..7] (1..8 on the physical switch panel) (top-to-bottom).
   //_\source /raw.githubusercontent.com/osfpga/VirtualFPGALab/35e36bd144fddd75495d4cbc01c4fc50ac5bde6f/tlvlib/tinytapeoutlib.tlv 82   // Instantiated from top.tlv, 286 as: m5+tt_input_labels_viz(⌈"Value[0]", "Value[1]", "Value[2]", "Value[3]", "Op[0]", "Op[1]", "Op[2]", "="⌉)
      for (input_label = 0; input_label <= 7; input_label++) begin : L1_InputLabel //_/input_label
         
      end
   //_\end_source

//_\SV
endmodule


// Undefine macros defined by SandPiper.
`undef BOGUS_USE
